### ISSUE TITLE
Add CSS class to annotated files, other touchup

### ISSUE THREAD

**Issue by efrec** [elias-sundqvist/obsidian-annotator#308]
I'm asking for these enhancements because I use the markdown view much more than the annotation mode, via embedding annotations where they're relevant in other notes. It would be nice to have more control over the appearance of the text.

I'd prefer something like the following CSS selector:
```css
.markdown-preview-view.obsidian-annotator blockquote * {}
```

Over these awkward ones:
```css
/* Safe to assume any blockquote containing only p>em>mark is an annotation. */

/* Style for mark/highlight */
.markdown-preview-view .el-blockquote>blockquote>p:only-child>em>mark {
    ...
}

/* Style for "show annotation" link; hacky way to move to own line */
.markdown-preview-view .el-blockquote>blockquote>p:only-child>em ~ a.internal-link {
    display: block;
}

/* Style for tags; hacky way to move tags to own line */
.markdown-preview-view .el-blockquote>blockquote>p:only-child>em~a.internal-link+a.tag::before {
    content: '\000A';
    white-space: pre;
}
```

I also can't easily style (don't know how I would, actually) the prefix, postfix, and comment. If the comment were in its own `p` element, that would resolve my issue.

I was able to make this look nice as-is, honestly. It could be better, though:

![image](https://user-images.githubusercontent.com/103912894/227757309-562c4daa-f026-4a18-9031-a502adeba313.png)
